version: "3.7"

services:
  mysql_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoecole
    ports:
      - "3355:3306"
    volumes:
      - ./data:/var/lib/mysql